### ISSUE TITLE
Proper transaction in the transaction page with pagination

### ISSUE THREAD

**Issue by raghav-rumsan** [rahataid/rahat-ui#883]

**Comment by Sanjil-rumsan** [comment]
Transaction is shown but pagination (rows per page and total  page not shown) needs to be fixed.

**Comment by Sanjil-rumsan** [comment]
- [ ] Need to change position of Rows per page and Page number to right currently it is showing in left  @bipinparajuli 
![Image](https://github.com/user-attachments/assets/09d40d2b-6334-458e-831e-3fb5368668a3)

**Comment by Sanjil-rumsan** [comment]
Fixed in dev and stage
